module.exports = {
    ROOM_ACTION_TYPES : [ 'SET_READY', 'SET_UNREADY', 'ADD_GAME', 'START_GAME' ],
    SET_READY_ACTION_TYPE : 'SET_READY',
    SET_UNREADY_ACTION_TYPE : 'SET_UNREADY',
    ADD_GAME_ACTION_TYPE : 'ADD_GAME',
    START_GAME_ACTION_TYPE : 'START_GAME',
    GAME_IDS : ['ROCK_PAPER_SCISSORS'],
    GAMES : {
        ROCK_PAPER_SCISSORS : require('./games/RockPaperScissors')
    }

}