export const USER_STATE_CHANGED = 'USER_STATE_CHANGED';
export const ID_TOKEN_CHANGED = 'ID_TOKEN_CHANGED';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const CREATE_ROOM = 'CREATE_ROOM';
export const JOIN_ROOM = 'JOIN_ROOM';
export const UPDATE_ROOM_STATE_SUCCESS = 'UPDATE_ROOM_STATE_SUCCESS';
export const UPDATE_ROOM_STATE_FAILURE = 'UPDATE_ROOM_STATE_FAILURE';