export const USER_STATE_CHANGED = 'USER_STATE_CHANGED';
export const ID_TOKEN_CHANGED = 'ID_TOKEN_CHANGED';
export const GET_USER_DATA_STARTED = 'GET_USER_DATA_STARTED';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';